name: Build, Push to Docker Hub and Deploy to Environments

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest

    - name: Logout from Docker Hub
      run: docker logout

  deploy_to_environments:
    needs: build_and_push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Stage, Release-Candidate, UAT, Production]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Checkout ${{ matrix.environment }} branch
      run: git checkout ${{ matrix.environment }}

    - name: Merge main into ${{ matrix.environment }}
      run: |
        git checkout ${{ matrix.environment }}
        git pull origin main
        git push origin ${{ matrix.environment }}

    - name: Deploy to ${{ matrix.environment }}
      run: |
        # Your deployment scripts or commands for each environment go here
        echo "Deploying to ${{ matrix.environment }}"

    - name: Push changes back to ${{ matrix.environment }}
      run: git push origin ${{ matrix.environment }}

      - name: Logout from Docker Hub
  run: docker logout

