name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This will trigger the action when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # This will trigger the action when a PR is created or updated targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code to the runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Enable Docker Buildx (multi-platform builds)

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use the Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use the Docker Hub password (access token) secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v2  # Build and push the Docker image
        with:
          context: .  # The context is the current directory (where your Dockerfile is located)
          file: ./Dockerfile  # The Dockerfile to use for building the image
          push: true  # Push the image to Docker Hub after building
          tags: ${{ secrets.DOCKER_USERNAME }}/client-gui-app:latest  # Tag for the Docker image
