name: Snyk Security Scan

on:
  push:
    branches:
      - main
      - dev
      - stage
      - uat
      - rc
      - production
  pull_request:
    branches:
      - main
      - dev
      - stage
      - uat
      - rc
      - production

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk test
        run: snyk test

      - name: Monitor Snyk
        run: snyk monitor
